# Default "production" profile.
# Reference build time 13s
[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 10000
evm_version = "cancun"
libs = ["lib"]
src = "contracts"
out = "out"
test = "test"
broadcast = "broadcast"
cache_path = "cache"
auto_detect_remappings = false
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
    "@prb/math/=lib/prb-math/src/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
    "upgrade-scripts/=lib/upgrade-scripts/src/",
    "UDS/=lib/upgrade-scripts/lib/UDS/src/"
]
fs_permissions = [
    { access = "read", path = "out"},
    { access = "read-write", path = "deployments"}
]

# Use FOUNDRY_PROFILE=lite for quicker compilation.
# Reference build time 6s
[profile.lite]
optimizer = false

# Use FOUNDRY_PROFILE=yul to use the "yul" intermediate representation for
# optimization. Caution - this is VERY slow!
# Reference build time 2m45s
[profile.yul]
via_ir = true

# Use FOUNDRY_PROFILE=yul-lite to use the "yul" intermediate representation
# without any optimization, for quicker compilation for tests.
# Reference build time 33s
[profile.yul-lite]
via_ir = true

[profile.yul-lite.optimizer_details.yulDetails]
optimizerSteps = ''

[fmt]
bracket_spacing = true

